import { Contact } from '../../types';

export let mockContacts: Contact[] = [
  { 
    id: 'contact1', 
    name: 'Иван Петров', 
    email: 'ivan.petrov@example.com', 
    phone: '79261234567', 
    companyName: 'ООО Ромашка', 
    city: 'Москва', 
    priority: '1', 
    isClient: true, 
    isSupplier: false, 
    isArchived: false, 
    requisites: {inn: '7701234567', name: 'ООО Ромашка Трейд', legalAddress: '123123, г. Москва, ул. Тверская, д. 1'}, 
    socialMedia: {telegram: 'ivan_petrov_tg'},
    isMoscowDelivery: true,
  },
  { 
    id: 'contact2', 
    name: 'Мария Сидорова', 
    email: 'maria.sidorova@example.com', 
    phone: '79169876543', 
    city: 'Санкт-Петербург', 
    priority: '2', 
    isClient: true, 
    isSupplier: false, 
    isArchived: false,
    isMoscowDelivery: false,
  },
  { 
    id: 'contact3', 
    name: 'Алексей Иванов', 
    companyName: 'ИП Иванов А.А.', 
    city: 'Казань', 
    priority: '3', 
    isClient: false, 
    isSupplier: true, 
    supplierType: 'Упаковка',
    isArchived: true, 
    archivedAt: new Date().toISOString(),
    isMoscowDelivery: false,
  },
  {
    id: 'contact4',
    name: 'ООО "ПромЗоны"',
    email: 'rent@promzony.com',
    phone: '74959998877',
    city: 'Москва',
    priority: null,
    isClient: false,
    isSupplier: true,
    supplierType: 'Аренда производственных площадей',
    isArchived: false,
    requisites: {
        inn: '7705555555',
        name: 'ООО "ПромЗоны"',
        legalAddress: 'г. Москва, ул. Промышленная, д. 10',
    },
    isMoscowDelivery: true,
  }
];