
import { Contact } from '../../types';

export let mockContacts: Contact[] = [
  { 
    id: 'contact1', 
    name: 'Иван Петров (Снабжение)', 
    email: 'ivan.petrov@example.com', 
    phone: '79261234567', 
    companyName: 'ООО Ромашка', 
    city: 'Москва', 
    priority: '1', 
    isClient: false, 
    isSupplier: true, 
    supplierType: 'Сырьё',
    isArchived: false, 
    requisites: {inn: '7701234567', name: 'ООО Ромашка Трейд', legalAddress: '123123, г. Москва, ул. Тверская, д. 1'}, 
    socialMedia: {telegram: 'ivan_petrov_tg'},
    isMoscowDelivery: true,
  },
  { 
    id: 'tech-1', 
    name: 'Николай Холодильщик', 
    phone: '79001112233', 
    companyName: 'РемХолод', 
    city: 'Москва', 
    priority: null, 
    isClient: false, 
    isSupplier: true, 
    supplierType: 'Технический специалист',
    notes: 'Лучший мастер по инкубаторам и морозилкам. Telegram: @ref_master',
    socialMedia: { telegram: 'ref_master' },
    isArchived: false, 
  },
  { 
    id: 'landlord-1', 
    name: 'Виктор Борисович (БЦ Луч)', 
    phone: '79114445566', 
    companyName: 'Бизнес-Центр "Луч"', 
    city: 'Москва', 
    priority: null, 
    isClient: false, 
    isSupplier: true, 
    supplierType: 'Арендодатель',
    notes: 'По вопросам аренды и электричества в цеху.',
    isArchived: false, 
  },
  { 
    id: 'contact2', 
    name: 'Мария Сидорова (Опт)', 
    email: 'maria.sidorova@example.com', 
    phone: '79169876543', 
    city: 'Санкт-Петербург', 
    priority: '2', 
    isClient: true, 
    isSupplier: false, 
    isArchived: false,
    isMoscowDelivery: false,
  }
];
