import { EquipmentItem } from '../../types';

export let mockEquipment: EquipmentItem[] = [
    {
        id: 'equip-1',
        name: 'Шелушилка сырья (комплекс)',
        category: 'Подготовка сырья',
        description: 'Комплекс из вакуумного загрузчика, мотора зернодробилки и пылесоса с циклоном для отделения шелухи.',
        powerKw: 5.5,
        usageType: 'on_demand',
        amortization: { method: 'percentage_of_income', cost: 350000, purchaseDate: '2023-01-15', amortizationPercentage: 2.5 },
        isArchived: false,
        createdAt: '2023-01-10T10:00:00Z',
        updatedAt: '2023-01-10T10:00:00Z',
        status: 'operational',
    },
    {
        id: 'equip-2',
        name: 'Соевая мойка',
        category: 'Подготовка сырья',
        description: 'Промышленная мойка для сырья.',
        powerKw: 1.5,
        usageType: 'on_demand',
        amortization: { method: 'percentage_of_income', cost: 120000, purchaseDate: '2023-02-20', amortizationPercentage: 1.0 },
        isArchived: false,
        createdAt: '2023-02-15T11:00:00Z',
        updatedAt: '2023-02-15T11:00:00Z',
        status: 'operational',
    },
    {
        id: 'equip-3',
        name: 'Индукционная плита #1',
        category: 'Термообработка',
        powerKw: 3.5,
        usageType: 'on_demand',
        amortization: { method: 'percentage_of_income', cost: 25000, purchaseDate: '2023-03-01', amortizationPercentage: 0.8 },
        isArchived: false,
        createdAt: '2023-03-01T12:00:00Z',
        updatedAt: '2023-03-01T12:00:00Z',
        status: 'in_use',
        currentProductionOrderId: 'PO-001',
    },
    {
        id: 'equip-3-2',
        name: 'Индукционная плита #2',
        category: 'Термообработка',
        powerKw: 3.5,
        usageType: 'on_demand',
        amortization: { method: 'percentage_of_income', cost: 25000, purchaseDate: '2023-03-01', amortizationPercentage: 0.8 },
        isArchived: false,
        createdAt: '2023-03-01T12:01:00Z',
        updatedAt: '2023-03-01T12:01:00Z',
        status: 'operational',
    },
    {
        id: 'equip-3-3',
        name: 'Индукционная плита #3',
        category: 'Термообработка',
        powerKw: 3.5,
        usageType: 'on_demand',
        amortization: { method: 'percentage_of_income', cost: 25000, purchaseDate: '2023-03-01', amortizationPercentage: 0.8 },
        isArchived: false,
        createdAt: '2023-03-01T12:02:00Z',
        updatedAt: '2023-03-01T12:02:00Z',
        status: 'maintenance',
    },
    {
        id: 'equip-4',
        name: '"Бетономешалка" пищевая',
        category: 'Смешивание и охлаждение',
        description: 'Смеситель из нержавеющей стали для сушки и смешивания сои.',
        powerKw: 2.2,
        usageType: 'on_demand',
        amortization: { method: 'percentage_of_income', cost: 180000, purchaseDate: '2023-04-10', amortizationPercentage: 1.2 },
        isArchived: false, // Un-archived
        createdAt: '2023-04-05T13:00:00Z',
        updatedAt: new Date().toISOString(),
        status: 'operational',
    },
     {
        id: 'equip-5',
        name: 'Термостат',
        category: 'Термообработка',
        description: 'Инкубационная камера для ферментации темпе.',
        powerKw: 2.0,
        usageType: 'on_demand',
        amortization: { method: 'percentage_of_income', cost: 250000, purchaseDate: '2023-05-15', amortizationPercentage: 2.0 },
        isArchived: false,
        createdAt: '2023-05-10T14:00:00Z',
        updatedAt: '2023-05-10T14:00:00Z',
        status: 'operational',
    },
    {
        id: 'equip-6',
        name: 'Вакуумный упаковщик',
        category: 'Упаковка',
        description: 'Камерный вакуумный упаковщик для готовой продукции.',
        powerKw: 1.2,
        usageType: 'on_demand',
        amortization: { method: 'percentage_of_income', cost: 95000, purchaseDate: '2023-06-01', amortizationPercentage: 0.9 },
        isArchived: false,
        createdAt: '2023-06-01T15:00:00Z',
        updatedAt: '2023-06-01T15:00:00Z',
        status: 'broken',
    },
    {
        id: 'equip-7',
        name: 'Морозильный шкаф',
        category: 'Хранение',
        powerKw: 0.8,
        usageType: 'continuous_24_7',
        amortization: { method: 'percentage_of_income', cost: 80000, purchaseDate: '2023-07-01', amortizationPercentage: 0.7 },
        isArchived: false,
        createdAt: '2023-07-01T10:00:00Z',
        updatedAt: '2023-07-01T10:00:00Z',
        status: 'operational',
        isStorageLocation: true,
    },
    {
        id: 'equip-8',
        name: 'Морозильный ларь',
        category: 'Хранение',
        powerKw: 0.5,
        usageType: 'continuous_24_7',
        amortization: { method: 'percentage_of_income', cost: 45000, purchaseDate: '2023-07-01', amortizationPercentage: 0.5 },
        isArchived: false,
        createdAt: '2023-07-01T10:05:00Z',
        updatedAt: '2023-07-01T10:05:00Z',
        status: 'operational',
        isStorageLocation: true,
    },
    {
        id: 'equip-9',
        name: 'Дегидратор',
        category: 'Термообработка',
        powerKw: 1.0,
        usageType: 'on_demand',
        amortization: { method: 'percentage_of_income', cost: 60000, purchaseDate: '2023-08-01', amortizationPercentage: 0.6 },
        isArchived: false,
        createdAt: '2023-08-01T11:00:00Z',
        updatedAt: '2023-08-01T11:00:00Z',
        status: 'operational',
    },
    {
        id: 'equip-10',
        name: 'Автоклав',
        category: 'Термообработка',
        powerKw: 4.0,
        usageType: 'on_demand',
        amortization: { method: 'percentage_of_income', cost: 450000, purchaseDate: '2023-09-01', amortizationPercentage: 3.0 },
        isArchived: false,
        createdAt: '2023-09-01T12:00:00Z',
        updatedAt: '2023-09-01T12:00:00Z',
        status: 'operational',
    },
    {
        id: 'equip-11',
        name: '"КоптУльня" КТД-50',
        category: 'Термообработка',
        description: 'Термодымовая камера КТД-50 для копчения продукции.',
        powerKw: 6.0,
        usageType: 'on_demand',
        amortization: { method: 'percentage_of_income', cost: 550000, purchaseDate: '2023-10-01', amortizationPercentage: 4.0 },
        isArchived: false,
        createdAt: '2023-10-01T13:00:00Z',
        updatedAt: '2023-10-01T13:00:00Z',
        status: 'operational',
    },
    {
        id: 'equip-12',
        name: 'Освещение цеха',
        category: 'Освещение',
        description: 'Система светодиодного освещения производственного помещения.',
        powerKw: 0.5,
        usageType: 'working_hours',
        amortization: { method: 'percentage_of_income', cost: 75000, purchaseDate: '2023-01-01', amortizationPercentage: 0.3 },
        isArchived: false,
        createdAt: '2023-01-01T14:00:00Z',
        updatedAt: '2023-01-01T14:00:00Z',
        status: 'operational',
    },
    {
        id: 'equip-13',
        name: 'Резервный холодильник',
        category: 'Хранение',
        powerKw: 0.7,
        usageType: 'continuous_24_7',
        amortization: { method: 'percentage_of_income', cost: 65000, purchaseDate: '2023-07-05', amortizationPercentage: 0.6 },
        isArchived: false,
        createdAt: '2023-07-05T10:00:00Z',
        updatedAt: '2023-07-05T10:00:00Z',
        status: 'operational',
        isStorageLocation: true,
    }
];