import { HouseholdItem } from '../../types';

export let mockHouseholdItems: HouseholdItem[] = [
  { id: 'HI001', name: 'Соевые бобы органические', category: 'Сырьё', quantity: 500, unit: 'кг', price: 150, lastUpdated: new Date().toISOString(), isArchived: false, lowStockThreshold: 100 },
  { id: 'HI002', name: 'Гречка зеленая', category: 'Сырьё', quantity: 200, unit: 'кг', price: 120, lastUpdated: new Date().toISOString(), isArchived: false, lowStockThreshold: 50 },
  { id: 'HI003', name: 'Нут (турецкий горох)', category: 'Сырьё', quantity: 150, unit: 'кг', price: 180, lastUpdated: new Date().toISOString(), isArchived: false },
  { id: 'HI004', name: 'Уксус яблочный 5%', category: 'Сырьё', quantity: 10, unit: 'л', price: 80, lastUpdated: new Date().toISOString(), isArchived: false },
  { id: 'HI005', name: 'Закваска Rhizopus Oligosporus', category: 'Сырьё', quantity: 2000, unit: 'гр', price: 10, notes: 'Хранить в холодильнике', lastUpdated: new Date().toISOString(), isArchived: false, lowStockThreshold: 500 },
  { id: 'HI006', name: 'Щепа ольховая для копчения (мелкая фракция)', category: 'Сырьё', quantity: 20, unit: 'кг', price: 250, lastUpdated: new Date().toISOString(), isArchived: false },
  { id: 'HI007', name: 'Соль морская пищевая', category: 'Специи', quantity: 5000, unit: 'гр', price: 0.1, lastUpdated: new Date().toISOString(), isArchived: false },
  { id: 'HI008', name: 'Глутамат натрия (усилитель вкуса)', category: 'Специи', quantity: 500, unit: 'гр', price: 1.5, lastUpdated: new Date().toISOString(), isArchived: false },
  { id: 'HI009', name: 'Паприка копченая молотая', category: 'Специи', quantity: 3000, unit: 'гр', price: 0.8, lastUpdated: new Date().toISOString(), isArchived: false },
  { id: 'HI010', name: 'Смесь специй "Для копченых чипсов"', category: 'Специи', quantity: 1000, unit: 'гр', price: 1.2, notes: 'Состав: паприка, чили, черный перец, кориандр', lastUpdated: new Date().toISOString(), isArchived: false },
  { id: 'HI011', name: 'Перец черный горошек', category: 'Специи', quantity: 2000, unit: 'гр', price: 1, lastUpdated: new Date().toISOString(), isArchived: false },
  { id: 'HI012', name: 'Кориандр молотый', category: 'Специи', quantity: 1000, unit: 'гр', price: 0.7, lastUpdated: new Date().toISOString(), isArchived: false },
  { id: 'HI013', name: 'Тмин семена', category: 'Специи', quantity: 1000, unit: 'гр', price: 0.9, lastUpdated: new Date().toISOString(), isArchived: false },
  { id: 'HI014', name: 'Чеснок сушеный гранулированный', category: 'Специи', quantity: 5000, unit: 'гр', price: 0.6, lastUpdated: new Date().toISOString(), isArchived: false },
  { id: 'HI015', name: 'Пакеты вакуумные 15x20см (для темпе)', category: 'Упаковка', quantity: 1500, unit: 'шт', price: 5, lastUpdated: new Date().toISOString(), isArchived: false, lowStockThreshold: 500 },
  { id: 'HI016', name: 'Этикетка "Темпе Классический" (самоклеящаяся)', category: 'Упаковка', quantity: 2000, unit: 'шт', price: 2, lastUpdated: new Date().toISOString(), isArchived: false },
  { id: 'HI017', name: 'Этикетка "Темпе Копченый" (самоклеящаяся)', category: 'Упаковка', quantity: 2000, unit: 'шт', price: 2, lastUpdated: new Date().toISOString(), isArchived: false },
  { id: 'HI018', name: 'Пакеты Дой-пак крафт с замком zip-lock (для чипсов, 100гр)', category: 'Упаковка', quantity: 1000, unit: 'шт', price: 7, lastUpdated: new Date().toISOString(), isArchived: false },
  { id: 'HI019', name: 'Этикетка "Темпе-Чипсы" (самоклеящаяся, универсальная)', category: 'Упаковка', quantity: 2000, unit: 'шт', price: 2, lastUpdated: new Date().toISOString(), isArchived: false },
  { id: 'HI020', name: 'Коробки картонные 30x20x15см (транспортные)', category: 'Упаковка', quantity: 300, unit: 'шт', price: 25, lastUpdated: new Date().toISOString(), isArchived: false },
  { id: 'HI021', name: 'Скотч упаковочный', category: 'Упаковка', quantity: 20, unit: 'рул', price: 80, lastUpdated: new Date().toISOString(), isArchived: false, lowStockThreshold: 5 },
  { id: 'HI022', name: 'Масло подсолнечное рафинированное (для жарки)', category: 'Масла', quantity: 50, unit: 'л', price: 110, lastUpdated: new Date().toISOString(), isArchived: false },
  { id: 'HI023', name: 'Швабра с отжимом', category: 'Хозы', quantity: 2, unit: 'шт', price: 1200, lastUpdated: new Date().toISOString(), isArchived: false, lowStockThreshold: 2 },
  { id: 'HI024', name: 'Мыло для рук жидкое (5л)', category: 'Хозы', quantity: 1, unit: 'кан', price: 450, lastUpdated: new Date().toISOString(), isArchived: false, lowStockThreshold: 2 },
  { id: 'HI025', name: 'Лампочки LED E27 15W', category: 'Электрика', quantity: 20, unit: 'шт', price: 90, lastUpdated: new Date().toISOString(), isArchived: false, lowStockThreshold: 10 },
];
