import { KanbanTask, KanbanTaskStatus } from '../../types';

export let mockKanbanTasks: KanbanTask[] = [
  { id: 'task1', title: 'Разработать новый вкус темпе', description: 'Эксперименты с нутом и чечевицей.', status: KanbanTaskStatus.TODO, assigneeId: 'user3', createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(), isArchived: false, subTasks: [], showInMyTasks: true, checklist: [], boardIds: ['board-default', 'board-dev'], taskStagePotentialHistory: [], taskStageContradictionsHistory: [], taskStageSolutionHistory: [] },
  { id: 'task2', title: 'Запустить рекламную кампанию в VK', description: 'Таргетинг на вегетарианцев и ЗОЖ.', status: KanbanTaskStatus.IN_PROGRESS, assigneeId: 'user4', dueDate: '2023-12-01', createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(), isArchived: false, activeTaskStage: 'Потенциал', taskStagePotentialHistory:[], taskStageContradictionsHistory:[], taskStageSolutionHistory:[], subTasks: [], showInMyTasks: true, checklist: [], boardIds: ['board-marketing'] },
  { id: 'task3', title: 'Провести инвентаризацию склада', description: 'Полный пересчет остатков.', status: KanbanTaskStatus.DONE, assigneeId: 'user2', createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(), isArchived: false, subTasks: [], showInMyTasks: true, checklist: [], boardIds: ['board-default'], taskStagePotentialHistory: [], taskStageContradictionsHistory: [], taskStageSolutionHistory: [] },
  { id: 'task4', title: 'Написать статью о пользе темпе', description: 'Для блога на сайте.', status: KanbanTaskStatus.TODO, assigneeId: null, priority: '2', createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(), isArchived: false, subTasks: [], showInMyTasks: false, checklist: [], boardIds: ['board-marketing'], taskStagePotentialHistory: [], taskStageContradictionsHistory: [], taskStageSolutionHistory: [] },
  { id: 'task5', title: 'Обновить дизайн упаковки', description: 'Сделать более современным и привлекательным.', status: KanbanTaskStatus.IN_PROGRESS, assigneeId: 'user1', priority: '1', complexity: 'high', createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(), isArchived: false, subTasks: [], showInMyTasks: true, checklist: [], boardIds: ['board-default', 'board-marketing'], taskStagePotentialHistory: [], taskStageContradictionsHistory: [], taskStageSolutionHistory: [] },
  { id: 'task6', title: 'Архивная задача на общей доске', description: 'Эта задача в архиве.', status: KanbanTaskStatus.DONE, assigneeId: 'user1', createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(), isArchived: true, archivedStatus: KanbanTaskStatus.DONE, archivedAt: new Date().toISOString(), subTasks: [], showInMyTasks: true, checklist: [], boardIds: ['board-default'], taskStagePotentialHistory: [], taskStageContradictionsHistory: [], taskStageSolutionHistory: [] },
];
