import { Transaction } from '../../types';
import { generateId } from '../../utils/idGenerators';

export let mockTransactions: Transaction[] = [
  {
    id: generateId('txn'),
    date: '2024-07-25',
    type: 'income',
    amount: 1300,
    description: 'Оплата от Мария Сидорова',
    category: 'Продажа товара',
    isTaxDeductible: undefined,
    relatedOrderId: 'order2',
    relatedContactId: 'contact2',
    relatedProductionOrderId: null,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    isArchived: false,
  },
  {
    id: generateId('txn'),
    date: '2024-07-24',
    type: 'expense',
    amount: 30000,
    description: 'Закупка соевых бобов у ООО Ромашка',
    category: 'Закупка сырья',
    isTaxDeductible: true,
    relatedPurchaseRequestId: 'PR-002',
    relatedContactId: 'contact1',
    relatedProductionOrderId: null,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    isArchived: false,
  },
  {
    id: generateId('txn'),
    date: '2024-07-01',
    type: 'expense',
    amount: 66760,
    description: 'Аренда производственного помещения за Июль',
    category: 'Аренда',
    isTaxDeductible: true,
    relatedContactId: null,
    relatedProductionOrderId: null,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    isArchived: false,
  },
   {
    id: generateId('txn'),
    date: '2024-07-10',
    type: 'expense',
    amount: 12000,
    description: 'Услуги клининга за месяц',
    category: 'Коммунальные услуги',
    isTaxDeductible: true,
    relatedContactId: null,
    relatedProductionOrderId: null,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    isArchived: false,
  },
  {
    id: generateId('txn'),
    date: '2024-07-15',
    type: 'expense',
    amount: 5000,
    description: 'Обед с семьей (личные траты)',
    category: 'Прочее',
    isTaxDeductible: false,
    relatedContactId: null,
    relatedProductionOrderId: null,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    isArchived: false,
  },
];