import { WarehouseItem } from '../../types';

export let mockWarehouseItems: WarehouseItem[] = [
  {
    id: 'TMP001', name: 'Темпе Классический Соевый 250гр', sku: 'TMP-SOY-CL-250', quantity: 100, price: 250, location: 'loc1',
    description: 'Классический темпе из соевых бобов.', lastUpdated: new Date().toISOString(), isArchived: false, 
    history: [
      { id: 'whh1', timestamp: new Date().toISOString(), userId: 'system', changeType: 'production_output', quantityChange: 50, newQuantity: 100, reason: 'Производство по ПЗ #PO-001' }
    ],
    shippingWeightGrams: 260,
    billOfMaterials: [
      { householdItemId: 'HI001', householdItemName: 'Соевые бобы органические', quantityPerUnit: 0.15, unit: 'кг' },
      { householdItemId: 'HI004', householdItemName: 'Уксус яблочный 5%', quantityPerUnit: 0.005, unit: 'л' },
      { householdItemId: 'HI005', householdItemName: 'Закваска Rhizopus Oligosporus', quantityPerUnit: 0.5, unit: 'гр' },
      { householdItemId: 'HI015', householdItemName: 'Пакеты вакуумные 15x20см (для темпе)', quantityPerUnit: 1, unit: 'шт' },
      { householdItemId: 'HI016', householdItemName: 'Этикетка "Темпе Классический" (самоклеящаяся)', quantityPerUnit: 1, unit: 'шт' },
    ],
    openIncidentsCount: 1,
    lowStockThreshold: 20,
  },
  {
    id: 'TMP002', name: 'Темпе Копченый Соевый 250гр', sku: 'TMP-SOY-SMK-250', quantity: 80, price: 280, location: 'loc1',
    description: 'Копченый темпе из соевых бобов с натуральным копчением.', lastUpdated: new Date().toISOString(), isArchived: false, history: [],
    shippingWeightGrams: 260,
    billOfMaterials: [
      { householdItemId: 'HI001', householdItemName: 'Соевые бобы органические', quantityPerUnit: 0.15, unit: 'кг' },
      { householdItemId: 'HI004', householdItemName: 'Уксус яблочный 5%', quantityPerUnit: 0.005, unit: 'л' },
      { householdItemId: 'HI005', householdItemName: 'Закваска Rhizopus Oligosporus', quantityPerUnit: 0.5, unit: 'гр' },
      { householdItemId: 'HI007', householdItemName: 'Соль морская пищевая', quantityPerUnit: 2, unit: 'гр' },
      { householdItemId: 'HI008', householdItemName: 'Глутамат натрия (усилитель вкуса)', quantityPerUnit: 0.5, unit: 'гр' },
      { householdItemId: 'HI006', householdItemName: 'Щепа ольховая для копчения (мелкая фракция)', quantityPerUnit: 0.05, unit: 'кг' },
      { householdItemId: 'HI015', householdItemName: 'Пакеты вакуумные 15x20см (для темпе)', quantityPerUnit: 1, unit: 'шт' },
      { householdItemId: 'HI017', householdItemName: 'Этикетка "Темпе Копченый" (самоклеящаяся)', quantityPerUnit: 1, unit: 'шт' },
    ],
    openIncidentsCount: 0,
    lowStockThreshold: 20,
  },
  {
    id: 'TMP003', name: 'Темпе Классический Гречневый 250гр', sku: 'TMP-GRCH-CL-250', quantity: 70, price: 260, location: 'loc2',
    description: 'Классический темпе из зеленой гречки.', lastUpdated: new Date().toISOString(), isArchived: false, history: [],
    shippingWeightGrams: 260,
    billOfMaterials: [
      { householdItemId: 'HI002', householdItemName: 'Гречка зеленая', quantityPerUnit: 0.15, unit: 'кг' },
      { householdItemId: 'HI004', householdItemName: 'Уксус яблочный 5%', quantityPerUnit: 0.005, unit: 'л' },
      { householdItemId: 'HI005', householdItemName: 'Закваска Rhizopus Oligosporus', quantityPerUnit: 0.5, unit: 'гр' },
      { householdItemId: 'HI015', householdItemName: 'Пакеты вакуумные 15x20см (для темпе)', quantityPerUnit: 1, unit: 'шт' },
      { householdItemId: 'HI016', householdItemName: 'Этикетка "Темпе Классический" (самоклеящаяся)', quantityPerUnit: 1, unit: 'шт' },
    ],
    openIncidentsCount: 2,
  },
    {
    id: 'TMP004', name: 'Темпе Классический Нутовый 250гр', sku: 'TMP-NUT-CL-250', quantity: 60, price: 270, location: 'loc2',
    description: 'Классический темпе из нута.', lastUpdated: new Date().toISOString(), isArchived: false, history: [],
    shippingWeightGrams: 260,
    billOfMaterials: [
      { householdItemId: 'HI003', householdItemName: 'Нут (турецкий горох)', quantityPerUnit: 0.15, unit: 'кг' },
      { householdItemId: 'HI004', householdItemName: 'Уксус яблочный 5%', quantityPerUnit: 0.005, unit: 'л' },
      { householdItemId: 'HI005', householdItemName: 'Закваска Rhizopus Oligosporus', quantityPerUnit: 0.5, unit: 'гр' },
      { householdItemId: 'HI015', householdItemName: 'Пакеты вакуумные 15x20см (для темпе)', quantityPerUnit: 1, unit: 'шт' },
      { householdItemId: 'HI016', householdItemName: 'Этикетка "Темпе Классический" (самоклеящаяся)', quantityPerUnit: 1, unit: 'шт' },
    ],
    openIncidentsCount: 0,
  },
  {
    id: 'TMP005', name: 'Темпе Копченый Гречневый 250гр', sku: 'TMP-GRCH-SMK-250', quantity: 10, price: 290, location: 'loc1',
    description: 'Копченый темпе из зеленой гречки.', lastUpdated: new Date().toISOString(), isArchived: false, history: [],
    shippingWeightGrams: 260,
    billOfMaterials: [
      { householdItemId: 'HI002', householdItemName: 'Гречка зеленая', quantityPerUnit: 0.15, unit: 'кг' },
      { householdItemId: 'HI004', householdItemName: 'Уксус яблочный 5%', quantityPerUnit: 0.005, unit: 'л' },
      { householdItemId: 'HI005', householdItemName: 'Закваска Rhizopus Oligosporus', quantityPerUnit: 0.5, unit: 'гр' },
      { householdItemId: 'HI007', householdItemName: 'Соль морская пищевая', quantityPerUnit: 2, unit: 'гр' },
      { householdItemId: 'HI008', householdItemName: 'Глутамат натрия (усилитель вкуса)', quantityPerUnit: 0.5, unit: 'гр' },
      { householdItemId: 'HI006', householdItemName: 'Щепа ольховая для копчения (мелкая фракция)', quantityPerUnit: 0.05, unit: 'кг' },
      { householdItemId: 'HI015', householdItemName: 'Пакеты вакуумные 15x20см (для темпе)', quantityPerUnit: 1, unit: 'шт' },
      { householdItemId: 'HI017', householdItemName: 'Этикетка "Темпе Копченый" (самоклеящаяся)', quantityPerUnit: 1, unit: 'шт' },
    ],
    lowStockThreshold: 15,
    openIncidentsCount: 0,
  },
    {
    id: 'TMP006', name: 'Темпе Копченый Нутовый 250гр', sku: 'TMP-NUT-SMK-250', quantity: 40, price: 300, location: 'loc2',
    description: 'Копченый темпе из нута.', lastUpdated: new Date().toISOString(), isArchived: false, history: [],
    shippingWeightGrams: 260,
    billOfMaterials: [
      { householdItemId: 'HI003', householdItemName: 'Нут (турецкий горох)', quantityPerUnit: 0.15, unit: 'кг' },
      { householdItemId: 'HI004', householdItemName: 'Уксус яблочный 5%', quantityPerUnit: 0.005, unit: 'л' },
      { householdItemId: 'HI005', householdItemName: 'Закваска Rhizopus Oligosporus', quantityPerUnit: 0.5, unit: 'гр' },
      { householdItemId: 'HI007', householdItemName: 'Соль морская пищевая', quantityPerUnit: 2, unit: 'гр' },
      { householdItemId: 'HI008', householdItemName: 'Глутамат натрия (усилитель вкуса)', quantityPerUnit: 0.5, unit: 'гр' },
      { householdItemId: 'HI006', householdItemName: 'Щепа ольховая для копчения (мелкая фракция)', quantityPerUnit: 0.05, unit: 'кг' },
      { householdItemId: 'HI015', householdItemName: 'Пакеты вакуумные 15x20см (для темпе)', quantityPerUnit: 1, unit: 'шт' },
      { householdItemId: 'HI017', householdItemName: 'Этикетка "Темпе Копченый" (самоклеящаяся)', quantityPerUnit: 1, unit: 'шт' },
    ],
    openIncidentsCount: 0,
  },
  {
    id: 'CHIP001', name: 'Темпе-Чипсы Классические Соевые 100гр', sku: 'CHIP-SOY-CL-100', quantity: 120, price: 180, location: 'loc3',
    description: 'Хрустящие чипсы из соевого темпе.', lastUpdated: new Date().toISOString(), isArchived: false, history: [],
    shippingWeightGrams: 100,
    billOfMaterials: [
      { householdItemId: 'HI001', householdItemName: 'Соевые бобы органические', quantityPerUnit: 0.08, unit: 'кг' },
      { householdItemId: 'HI004', householdItemName: 'Уксус яблочный 5%', quantityPerUnit: 0.002, unit: 'л' },
      { householdItemId: 'HI005', householdItemName: 'Закваска Rhizopus Oligosporus', quantityPerUnit: 0.25, unit: 'гр' },
      { householdItemId: 'HI022', householdItemName: 'Масло подсолнечное рафинированное (для жарки)', quantityPerUnit: 0.02, unit: 'л' },
      { householdItemId: 'HI018', householdItemName: 'Пакеты Дой-пак крафт с замком zip-lock (для чипсов, 100гр)', quantityPerUnit: 1, unit: 'шт' },
      { householdItemId: 'HI019', householdItemName: 'Этикетка "Темпе-Чипсы" (самоклеящаяся, универсальная)', quantityPerUnit: 1, unit: 'шт' },
    ],
    openIncidentsCount: 0,
  },
  {
    id: 'CHIP002', name: 'Темпе-Чипсы Копченые Соевые (со специями) 100гр', sku: 'CHIP-SOY-SMKSP-100', quantity: 90, price: 200, location: 'loc3',
    description: 'Пикантные копченые чипсы из соевого темпе со специями.', lastUpdated: new Date().toISOString(), isArchived: false, history: [],
    shippingWeightGrams: 100,
    billOfMaterials: [
      { householdItemId: 'HI001', householdItemName: 'Соевые бобы органические', quantityPerUnit: 0.08, unit: 'кг' },
      { householdItemId: 'HI004', householdItemName: 'Уксус яблочный 5%', quantityPerUnit: 0.002, unit: 'л' },
      { householdItemId: 'HI005', householdItemName: 'Закваска Rhizopus Oligosporus', quantityPerUnit: 0.25, unit: 'гр' },
      { householdItemId: 'HI010', householdItemName: 'Смесь специй "Для копченых чипсов"', quantityPerUnit: 5, unit: 'гр' },
      { householdItemId: 'HI022', householdItemName: 'Масло подсолнечное рафинированное (для жарки)', quantityPerUnit: 0.02, unit: 'л' },
      { householdItemId: 'HI018', householdItemName: 'Пакеты Дой-пак крафт с замком zip-lock (для чипсов, 100гр)', quantityPerUnit: 1, unit: 'шт' },
      { householdItemId: 'HI019', householdItemName: 'Этикетка "Темпе-Чипсы" (самоклеящаяся, универсальная)', quantityPerUnit: 1, unit: 'шт' },
    ],
    openIncidentsCount: 0,
  },
  {
    id: 'CHIP003', name: 'Темпе-Чипсы Гречневые с Паприкой 100гр', sku: 'CHIP-GRCH-PAP-100', quantity: 70, price: 190, location: 'loc3',
    description: 'Чипсы из гречневого темпе с копченой паприкой.', lastUpdated: new Date().toISOString(), isArchived: false, history: [],
    shippingWeightGrams: 100,
    billOfMaterials: [
      { householdItemId: 'HI002', householdItemName: 'Гречка зеленая', quantityPerUnit: 0.08, unit: 'кг' },
      { householdItemId: 'HI004', householdItemName: 'Уксус яблочный 5%', quantityPerUnit: 0.002, unit: 'л' },
      { householdItemId: 'HI005', householdItemName: 'Закваска Rhizopus Oligosporus', quantityPerUnit: 0.25, unit: 'гр' },
      { householdItemId: 'HI009', householdItemName: 'Паприка копченая молотая', quantityPerUnit: 3, unit: 'гр' },
      { householdItemId: 'HI022', householdItemName: 'Масло подсолнечное рафинированное (для жарки)', quantityPerUnit: 0.02, unit: 'л' },
      { householdItemId: 'HI018', householdItemName: 'Пакеты Дой-пак крафт с замком zip-lock (для чипсов, 100гр)', quantityPerUnit: 1, unit: 'шт' },
      { householdItemId: 'HI019', householdItemName: 'Этикетка "Темпе-Чипсы" (самоклеящаяся, универсальная)', quantityPerUnit: 1, unit: 'шт' },
    ],
    openIncidentsCount: 0,
  },
  {
    id: 'CHIP004', name: 'Темпе-Чипсы Нутовые с Морской Солью 100гр', sku: 'CHIP-NUT-SALT-100', quantity: 60, price: 195, location: 'loc4',
    description: 'Чипсы из нутового темпе с морской солью.', lastUpdated: new Date().toISOString(), isArchived: false, history: [],
    shippingWeightGrams: 100,
    billOfMaterials: [
      { householdItemId: 'HI003', householdItemName: 'Нут (турецкий горох)', quantityPerUnit: 0.08, unit: 'кг' },
      { householdItemId: 'HI004', householdItemName: 'Уксус яблочный 5%', quantityPerUnit: 0.002, unit: 'л' },
      { householdItemId: 'HI005', householdItemName: 'Закваска Rhizopus Oligosporus', quantityPerUnit: 0.25, unit: 'гр' },
      { householdItemId: 'HI007', householdItemName: 'Соль морская пищевая', quantityPerUnit: 1, unit: 'гр' },
      { householdItemId: 'HI022', householdItemName: 'Масло подсолнечное рафинированное (для жарки)', quantityPerUnit: 0.02, unit: 'л' },
      { householdItemId: 'HI018', householdItemName: 'Пакеты Дой-пак крафт с замком zip-lock (для чипсов, 100гр)', quantityPerUnit: 1, unit: 'шт' },
      { householdItemId: 'HI019', householdItemName: 'Этикетка "Темпе-Чипсы" (самоклеящаяся, универсальная)', quantityPerUnit: 1, unit: 'шт' },
    ],
    openIncidentsCount: 0,
  },
];